// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RallyAPI.Orders.Infrastructure;

#nullable disable

namespace RallyAPI.Orders.Infrastructure.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20260305110647_AddOrderEscalationFields")]
    partial class AddOrderEscalationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orders")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RallyAPI.Orders.Domain.Entities.DeliveryInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<double?>("DistanceKm")
                        .HasPrecision(8, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("distance_km");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_minutes");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_at");

                    b.Property<string>("PickupAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pickup_address");

                    b.Property<string>("PickupContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pickup_contact_phone");

                    b.Property<string>("PickupPincode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pickup_pincode");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_name");

                    b.Property<string>("QuoteId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("quote_id");

                    b.Property<DateTime?>("QuotedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quoted_at");

                    b.Property<Guid?>("RiderId")
                        .HasColumnType("uuid")
                        .HasColumnName("rider_id");

                    b.Property<string>("RiderName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rider_name");

                    b.Property<string>("RiderPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rider_phone");

                    b.Property<string>("TrackingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tracking_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_delivery_info_order_id");

                    b.HasIndex("RiderId")
                        .HasDatabaseName("ix_delivery_info_rider_id");

                    b.ToTable("delivery_info", "orders");
                });

            modelBuilder.Entity("RallyAPI.Orders.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cancellation_notes");

                    b.Property<int?>("CancellationReason")
                        .HasColumnType("integer")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("customer_email");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_phone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("DeliveryQuoteId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EscalatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("escalated_at");

                    b.Property<string>("EscalationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("escalation_reason");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("internal_notes");

                    b.Property<bool>("IsEscalated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_escalated");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.Property<string>("PaymentId")
                        .HasColumnType("text");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("payment_status");

                    b.Property<string>("PaymentTransactionId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_at");

                    b.Property<DateTime?>("PreparingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preparing_at");

                    b.Property<DateTime?>("ReadyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_at");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("restaurant_name");

                    b.Property<string>("RestaurantPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("restaurant_phone");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("special_instructions");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_orders_created_at");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_orders_customer_id");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_order_number");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("ix_orders_restaurant_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_orders_status");

                    b.ToTable("orders", "orders");
                });

            modelBuilder.Entity("RallyAPI.Orders.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("ItemDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("item_description");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("item_name");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_item_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("special_instructions");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.ToTable("order_items", "orders");
                });

            modelBuilder.Entity("RallyAPI.Orders.Domain.Entities.DeliveryInfo", b =>
                {
                    b.HasOne("RallyAPI.Orders.Domain.Entities.Order", null)
                        .WithOne("DeliveryInfo")
                        .HasForeignKey("RallyAPI.Orders.Domain.Entities.DeliveryInfo", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("RallyAPI.Orders.Domain.ValueObjects.Money", "QuotedDeliveryFee", b1 =>
                        {
                            b1.Property<Guid>("DeliveryInfoId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("quoted_delivery_fee");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("INR")
                                .HasColumnName("quoted_delivery_fee_currency");

                            b1.HasKey("DeliveryInfoId");

                            b1.ToTable("delivery_info", "orders");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryInfoId");
                        });

                    b.OwnsOne("RallyAPI.Orders.Domain.ValueObjects.Address", "DeliveryAddress", b1 =>
                        {
                            b1.Property<Guid>("DeliveryInfoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BuildingName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("delivery_building_name");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("delivery_city");

                            b1.Property<string>("ContactPhone")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("delivery_contact_phone");

                            b1.Property<string>("Floor")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("delivery_floor");

                            b1.Property<string>("Instructions")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("delivery_instructions");

                            b1.Property<string>("Landmark")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("delivery_landmark");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("delivery_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("delivery_longitude");

                            b1.Property<string>("Pincode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("delivery_pincode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("delivery_street");

                            b1.HasKey("DeliveryInfoId");

                            b1.ToTable("delivery_info", "orders");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryInfoId");
                        });

                    b.OwnsOne("RallyAPI.Orders.Domain.ValueObjects.GeoCoordinate", "PickupLocation", b1 =>
                        {
                            b1.Property<Guid>("DeliveryInfoId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("pickup_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("pickup_longitude");

                            b1.HasKey("DeliveryInfoId");

                            b1.ToTable("delivery_info", "orders");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryInfoId");
                        });

                    b.Navigation("DeliveryAddress")
                        .IsRequired();

                    b.Navigation("PickupLocation")
                        .IsRequired();

                    b.Navigation("QuotedDeliveryFee");
                });

            modelBuilder.Entity("RallyAPI.Orders.Domain.Entities.Order", b =>
                {
                    b.OwnsOne("RallyAPI.Orders.Domain.ValueObjects.OrderPricing", "Pricing", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DiscountCode")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("discount_code");

                            b1.Property<string>("DiscountDescription")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("discount_description");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders", "orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("RallyAPI.Orders.Domain.ValueObjects.Money", "DeliveryFee", b2 =>
                                {
                                    b2.Property<Guid>("OrderPricingOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("delivery_fee");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasDefaultValue("INR")
                                        .HasColumnName("delivery_fee_currency");

                                    b2.HasKey("OrderPricingOrderId");

                                    b2.ToTable("orders", "orders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderPricingOrderId");
                                });

                            b1.OwnsOne("RallyAPI.Orders.Domain.ValueObjects.Money", "Discount", b2 =>
                                {
                                    b2.Property<Guid>("OrderPricingOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("discount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasDefaultValue("INR")
                                        .HasColumnName("discount_currency");

                                    b2.HasKey("OrderPricingOrderId");

                                    b2.ToTable("orders", "orders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderPricingOrderId");
                                });

                            b1.OwnsOne("RallyAPI.Orders.Domain.ValueObjects.Money", "PackagingFee", b2 =>
                                {
                                    b2.Property<Guid>("OrderPricingOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("packaging_fee");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasDefaultValue("INR")
                                        .HasColumnName("packaging_fee_currency");

                                    b2.HasKey("OrderPricingOrderId");

                                    b2.ToTable("orders", "orders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderPricingOrderId");
                                });

                            b1.OwnsOne("RallyAPI.Orders.Domain.ValueObjects.Money", "ServiceFee", b2 =>
                                {
                                    b2.Property<Guid>("OrderPricingOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("service_fee");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasDefaultValue("INR")
                                        .HasColumnName("service_fee_currency");

                                    b2.HasKey("OrderPricingOrderId");

                                    b2.ToTable("orders", "orders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderPricingOrderId");
                                });

                            b1.OwnsOne("RallyAPI.Orders.Domain.ValueObjects.Money", "SubTotal", b2 =>
                                {
                                    b2.Property<Guid>("OrderPricingOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("sub_total");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("currency");

                                    b2.HasKey("OrderPricingOrderId");

                                    b2.ToTable("orders", "orders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderPricingOrderId");
                                });

                            b1.OwnsOne("RallyAPI.Orders.Domain.ValueObjects.Money", "Tax", b2 =>
                                {
                                    b2.Property<Guid>("OrderPricingOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("tax");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasDefaultValue("INR")
                                        .HasColumnName("tax_currency");

                                    b2.HasKey("OrderPricingOrderId");

                                    b2.ToTable("orders", "orders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderPricingOrderId");
                                });

                            b1.OwnsOne("RallyAPI.Orders.Domain.ValueObjects.Money", "Tip", b2 =>
                                {
                                    b2.Property<Guid>("OrderPricingOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("tip");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasDefaultValue("INR")
                                        .HasColumnName("tip_currency");

                                    b2.HasKey("OrderPricingOrderId");

                                    b2.ToTable("orders", "orders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderPricingOrderId");
                                });

                            b1.OwnsOne("RallyAPI.Orders.Domain.ValueObjects.Money", "Total", b2 =>
                                {
                                    b2.Property<Guid>("OrderPricingOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("total");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasDefaultValue("INR")
                                        .HasColumnName("total_currency");

                                    b2.HasKey("OrderPricingOrderId");

                                    b2.ToTable("orders", "orders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderPricingOrderId");
                                });

                            b1.Navigation("DeliveryFee")
                                .IsRequired();

                            b1.Navigation("Discount")
                                .IsRequired();

                            b1.Navigation("PackagingFee")
                                .IsRequired();

                            b1.Navigation("ServiceFee")
                                .IsRequired();

                            b1.Navigation("SubTotal")
                                .IsRequired();

                            b1.Navigation("Tax")
                                .IsRequired();

                            b1.Navigation("Tip")
                                .IsRequired();

                            b1.Navigation("Total")
                                .IsRequired();
                        });

                    b.Navigation("Pricing")
                        .IsRequired();
                });

            modelBuilder.Entity("RallyAPI.Orders.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("RallyAPI.Orders.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("RallyAPI.Orders.Domain.ValueObjects.Money", "TotalPrice", b1 =>
                        {
                            b1.Property<Guid>("OrderItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("total_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("INR")
                                .HasColumnName("total_price_currency");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("order_items", "orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.OwnsOne("RallyAPI.Orders.Domain.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("OrderItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("unit_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("order_items", "orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("TotalPrice")
                        .IsRequired();

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("RallyAPI.Orders.Domain.Entities.Order", b =>
                {
                    b.Navigation("DeliveryInfo")
                        .IsRequired();

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
