// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RallyAPI.Delivery.Infrastructure.Persistence;

#nullable disable

namespace RallyAPI.Delivery.Infrastructure.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    [Migration("20260504221736_AddRtoStatesAndIgmTickets")]
    partial class AddRtoStatesAndIgmTickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("delivery")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RallyAPI.Delivery.Domain.Entities.DeliveryQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("base_fee");

                    b.Property<string>("BreakdownJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("breakdown");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("distance_km");

                    b.Property<double>("DropLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("drop_latitude");

                    b.Property<double>("DropLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("drop_longitude");

                    b.Property<string>("DropPincode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("drop_pincode");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_minutes");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<decimal>("FinalFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("final_fee");

                    b.Property<int>("FleetType")
                        .HasColumnType("integer")
                        .HasColumnName("fleet_type");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<decimal>("OrderAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("order_amount");

                    b.Property<double>("PickupLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("pickup_latitude");

                    b.Property<double>("PickupLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("pickup_longitude");

                    b.Property<string>("PickupPincode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pickup_pincode");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_name");

                    b.Property<string>("ProviderQuoteId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_quote_id");

                    b.Property<Guid?>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<decimal>("SurgeMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("surge_multiplier");

                    b.Property<string>("SurgeReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("surge_reason");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid?>("UsedForOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("used_for_order_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_quotes_expires_at");

                    b.HasIndex("IsUsed")
                        .HasDatabaseName("ix_quotes_is_used");

                    b.HasIndex("UsedForOrderId")
                        .HasDatabaseName("ix_quotes_order_id");

                    b.ToTable("quotes", "delivery");
                });

            modelBuilder.Entity("RallyAPI.Delivery.Domain.Entities.DeliveryRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ActualPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("actual_price");

                    b.Property<DateTime?>("ArrivedDropAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrived_drop_at");

                    b.Property<DateTime?>("ArrivedPickupAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrived_pickup_at");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("DeliveryInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("delivery_instructions");

                    b.Property<DateTime?>("DispatchAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatch_at");

                    b.Property<decimal?>("DistanceKm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("distance_km");

                    b.Property<string>("DropAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("drop_address");

                    b.Property<string>("DropCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("drop_code");

                    b.Property<string>("DropContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("drop_contact_name");

                    b.Property<string>("DropContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("drop_contact_phone");

                    b.Property<double>("DropLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("drop_latitude");

                    b.Property<double>("DropLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("drop_longitude");

                    b.Property<string>("DropPincode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("drop_pincode");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_minutes");

                    b.Property<string>("ExternalLspName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_lsp_name");

                    b.Property<string>("ExternalRiderName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_rider_name");

                    b.Property<string>("ExternalRiderPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("external_rider_phone");

                    b.Property<string>("ExternalTaskId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_task_id");

                    b.Property<string>("ExternalTrackingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_tracking_url");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailureNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_notes");

                    b.Property<string>("FailurePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_photo_url");

                    b.Property<int?>("FailureReason")
                        .HasColumnType("integer")
                        .HasColumnName("failure_reason");

                    b.Property<int?>("FleetType")
                        .HasColumnType("integer")
                        .HasColumnName("fleet_type");

                    b.Property<int?>("ItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("item_count");

                    b.Property<DateTime?>("LastLocationUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_location_updated_at");

                    b.Property<double?>("LastRiderLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("last_rider_latitude");

                    b.Property<double?>("LastRiderLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("last_rider_longitude");

                    b.Property<int>("OrderCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("order_category");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.Property<int>("OwnFleetAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("own_fleet_attempts");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_at");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pickup_address");

                    b.Property<string>("PickupCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pickup_code");

                    b.Property<string>("PickupContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pickup_contact_name");

                    b.Property<string>("PickupContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pickup_contact_phone");

                    b.Property<double>("PickupLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("pickup_latitude");

                    b.Property<double>("PickupLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("pickup_longitude");

                    b.Property<string>("PickupPincode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pickup_pincode");

                    b.Property<decimal?>("PriceDifference")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_difference");

                    b.Property<Guid?>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<decimal>("QuotedPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("quoted_price");

                    b.Property<Guid?>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<Guid?>("RiderId")
                        .HasColumnType("uuid")
                        .HasColumnName("rider_id");

                    b.Property<string>("RiderName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rider_name");

                    b.Property<string>("RiderPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rider_phone");

                    b.Property<DateTime?>("RtoDeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rto_delivered_at");

                    b.Property<DateTime?>("RtoDisposedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rto_disposed_at");

                    b.Property<DateTime?>("RtoInitiatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rto_initiated_at");

                    b.Property<DateTime?>("SearchingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("searching_started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DispatchAt")
                        .HasDatabaseName("ix_delivery_requests_dispatch_at");

                    b.HasIndex("ExternalTaskId")
                        .HasDatabaseName("ix_delivery_requests_external_task_id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_delivery_requests_order_id");

                    b.HasIndex("RiderId")
                        .HasDatabaseName("ix_delivery_requests_rider_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_delivery_requests_status");

                    b.ToTable("delivery_requests", "delivery");
                });

            modelBuilder.Entity("RallyAPI.Delivery.Domain.Entities.IgmTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("DeliveryRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_request_id");

                    b.Property<string>("DescriptionLong")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description_long");

                    b.Property<string>("DescriptionShort")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description_short");

                    b.Property<string>("ExternalIssueId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_issue_id");

                    b.Property<int>("IssueType")
                        .HasColumnType("integer")
                        .HasColumnName("issue_type");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.Property<DateTime?>("PushedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pushed_at");

                    b.Property<Guid>("RaisedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("raised_by_admin_id");

                    b.Property<string>("Rating")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rating");

                    b.Property<decimal?>("RefundAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("refund_amount");

                    b.Property<bool?>("RefundByLsp")
                        .HasColumnType("boolean")
                        .HasColumnName("refund_by_lsp");

                    b.Property<bool?>("RefundToClient")
                        .HasColumnType("boolean")
                        .HasColumnName("refund_to_client");

                    b.Property<int?>("ResolutionAction")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_action");

                    b.Property<string>("ResolutionLongDesc")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("resolution_long_desc");

                    b.Property<string>("ResolutionShortDesc")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resolution_short_desc");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sub_category");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryRequestId")
                        .HasDatabaseName("ix_igm_tickets_delivery_request_id");

                    b.HasIndex("ExternalIssueId")
                        .HasDatabaseName("ix_igm_tickets_external_issue_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_igm_tickets_order_id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_igm_tickets_state");

                    b.ToTable("igm_tickets", "delivery");
                });

            modelBuilder.Entity("RallyAPI.Delivery.Domain.Entities.RiderOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeliveryRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_request_id");

                    b.Property<decimal?>("DistanceToRestaurantKm")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("distance_to_restaurant_km");

                    b.Property<decimal>("Earnings")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("earnings");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("NotificationDelivered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("notification_delivered");

                    b.Property<DateTime?>("NotificationSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notification_sent_at");

                    b.Property<DateTime>("OfferedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offered_at");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<Guid>("RiderId")
                        .HasColumnType("uuid")
                        .HasColumnName("rider_id");

                    b.Property<double?>("RiderLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("rider_latitude");

                    b.Property<double?>("RiderLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("rider_longitude");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryRequestId")
                        .HasDatabaseName("ix_rider_offers_delivery_request_id");

                    b.HasIndex("RiderId")
                        .HasDatabaseName("ix_rider_offers_rider_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_rider_offers_status");

                    b.HasIndex("RiderId", "Status")
                        .HasDatabaseName("ix_rider_offers_rider_status");

                    b.ToTable("rider_offers", "delivery");
                });

            modelBuilder.Entity("RallyAPI.Delivery.Domain.Entities.RiderOffer", b =>
                {
                    b.HasOne("RallyAPI.Delivery.Domain.Entities.DeliveryRequest", null)
                        .WithMany("RiderOffers")
                        .HasForeignKey("DeliveryRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RallyAPI.Delivery.Domain.Entities.DeliveryRequest", b =>
                {
                    b.Navigation("RiderOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
